name: Deploiement VLAN avec Nornir (Local Auth)

on:
  push:
    branches:
      - main

jobs:
  deploy_vlan:
    runs-on: self-hosted

    steps:
      # 1. Récupérer le code (y compris ton hosts.yaml)
      - name: Checkout du code
        uses: actions/checkout@v4

      # 4. Lancer le script (Nornir lira le hosts.yaml automatiquement)
      - name: Execution du script Nornir
        run: |
          /home/idriss/Network_Automation/venv/bin/python3.12 create_vlan.py
